name: 'Cache Nx 📦'
description: 'Cache Nx build results'

inputs:
  lockfile:
    description: 'Path to the lockfile'
    default: 'yarn.lock'

runs:
  using: composite
  steps:
    - name: 'Cache Nx'
      uses: actions/cache@v3
      with:
        path: node_modules/.cache/nx
        key: ${{ runner.os }}-cache-nx-${{ hashFiles('${{ inputs.lockfile }}') }}-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-cache-nx-${{ hashFiles('${{ inputs.lockfile }}') }}-
          ${{ runner.os }}-cache-nx-
