# TODO: Remove this action in v5
name: 'Cache Nx 📦'
description: 'Cache Nx build results'

runs:
  using: composite
  steps:
    - uses: myparcelnl/actions/deprecated@v4
      with:
        name: 'myparcelnl/cache-nx'
        replacement: 'myparcelnl/nx-cache'

    - uses: myparcelnl/actions/nx-cache@v4
