name: 'Cache Nx 📦'
description: 'Cache Nx build results'

runs:
  using: composite
  steps:
    - uses: myparcelnl/actions/deprecated@v4
      with:
        name: 'cache-nx'
        replacement: 'nx-cache'

    - uses: myparcelnl/actions/nx-cache@v4
