name: 'Cache Nx 📦'
description: 'Cache Nx build results'

runs:
  using: composite
  steps:
    - name: 'Cache Nx'
      uses: actions/cache@v4
      with:
        path: node_modules/.cache/nx
        key: ${{ runner.os }}-cache-nx-${{ hashFiles('nx.json') }}-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-cache-nx-${{ hashFiles('nx.json') }}-
          ${{ runner.os }}-cache-nx-
