name: 'Generate app credentials'
description: 'Generate credentials and git committer details for a GitHub app.'

inputs:
  app-id:
    description: 'The app ID of the app.'
    required: true

  private-key:
    description: 'The private key of the app.'
    required: true

outputs:
  name:
    description: 'The name of the app.'
    value: ${{ steps.create-outputs.outputs.name }}

  token:
    description: 'The GitHub token of the app.'
    value: ${{ steps.create-outputs.outputs.token }}

  git-name:
    description: 'The name to use with git.'
    value: ${{ steps.create-outputs.outputs.git-name }}

  git-email:
    description: 'The email to use with git.'
    value: ${{ steps.create-outputs.outputs.git-email }}

runs:
  using: composite
  steps:
    - uses: wow-actions/use-app-token@d7957e08172ca2e8e49b35b8d266ad585885edc7
      id: generate-token
      with:
        app_id: ${{ inputs.app-id }}
        private_key: ${{ inputs.private-key }}

    - name: 'Set outputs'
      id: create-outputs
      shell: bash
      env:
        BOT_NAME: ${{ steps.generate-token.outputs.BOT_NAME }}
        BOT_TOKEN: ${{ steps.generate-token.outputs.BOT_TOKEN }}
      #language=bash
      run: |
        botGitName="$BOT_NAME[bot]"
        botGitEmail="$BOT_NAME[bot]@users.noreply.github.com"

        echo "name=$BOT_NAME" >> $GITHUB_OUTPUT
        echo "token=$BOT_TOKEN" >> $GITHUB_OUTPUT
        echo "git-name=$botGitName" >> $GITHUB_OUTPUT
        echo "git-email=$botGitEmail" >> $GITHUB_OUTPUT
