name: 'Generate app credentials'
description: 'Generate credentials and git committer details for a GitHub app.'

inputs:
  app-id:
    description: 'The app ID of the app.'
    required: true

  private-key:
    description: 'The private key of the app.'
    required: true

outputs:
  name:
    description: 'The name of the app.'
    value: ${{ steps.create-outputs.outputs.name }}

  token:
    description: 'The GitHub token of the app.'
    value: ${{ steps.create-outputs.outputs.token }}

  git-name:
    description: 'The name to use with git.'
    value: ${{ steps.create-outputs.outputs.git-name }}

  git-email:
    description: 'The email to use with git.'
    value: ${{ steps.create-outputs.outputs.git-email }}

runs:
  using: composite
  steps:
    - uses: wow-actions/use-app-token@v2
      id: generate-token
      with:
        app_id: ${{ inputs.app-id }}
        private_key: ${{ inputs.private-key }}

    - name: 'Set outputs'
      id: create-outputs
      shell: bash
      run: |
        bot_name=${{ steps.generate-token.outputs.BOT_NAME }}
        bot_git_name="${bot_name}[bot]"
        bot_git_email="${bot_name}[bot]@users.noreply.github.com"

        echo "name=${bot_name}" >> $GITHUB_OUTPUT
        echo "token=${{ steps.generate-token.outputs.BOT_TOKEN }}" >> $GITHUB_OUTPUT
        echo "git-name=${bot_git_name}" >> $GITHUB_OUTPUT
        echo "git-email=${bot_git_email}" >> $GITHUB_OUTPUT
