name: 'Generate app credentials'
description: 'Generate credentials and git committer details for a GitHub app.'

inputs:
  app-id:
    description: 'The app ID of the app.'
    required: true

  private-key:
    description: 'The private key of the app.'
    required: true

outputs:
  name:
    description: 'The name of the app.'
    value: ${{ steps.generate-token.outputs.app-slug }}

  token:
    description: 'The GitHub token of the app.'
    value: ${{ steps.generate-token.outputs.token }}

  git-name:
    description: 'The name to use with git.'
    value: ${{ steps.generate-token.outputs.app-slug }}

  git-email:
    description: 'The email to use with git.'
    value: ${{ steps.create-outputs.outputs.git-email }}

runs:
  using: composite
  steps:
    - uses: actions/create-github-app-token@v1
      id: generate-token
      with:
        app-id: ${{ inputs.app-id }}
        private-key: ${{ inputs.private-key }}

    - name: 'Set outputs'
      id: create-outputs
      shell: bash
      env:
        APP_SLUG: ${{ steps.generate-token.outputs.app-slug }}
      #language=bash
      run: |
        echo "git-email=$APP_SLUG@users.noreply.github.com" >> $GITHUB_OUTPUT
