name: 'Run PDK app builder'
description: 'Run @myparcel-pdk/app-builder'

inputs:
  command:
    description: 'Command to run'
    required: true

  image:
    description: 'PHP Docker image to use'
    required: false

  args:
    description: 'Additional arguments to pass to the command. Should be multiline string.'
    required: false

  env-file:
    description: 'The filename of the env file to use. Will be created if not passed and image is set.'
    required: false

runs:
  using: composite
  steps:
    - uses: myparcelnl/actions/composer-create-env-file@v5
      if: inputs.image != '' && inputs.env-file == ''
      id: env

    - uses: myparcelnl/actions/pdk-create-docker-command@v5
      if: inputs.image != ''
      id: prepare
      with:
        env-file: ${{ inputs.env-file || steps.env.outputs.filename }}
        image: ${{ inputs.image }}

    - uses: myparcelnl/actions/format-string@v5
      id: args
      with:
        mode: 'args'
        string: |
          ${{ inputs.args }}
          ${{ runner.debug == '1' && '-vvv' || '' }}

    - shell: bash
      env:
        ARGS: ${{ steps.args.outputs.string }}
        COMMAND: ${{ inputs.command }}
        DOCKER_COMMAND: ${{ steps.prepare.outputs.docker-command }}
        FORCE_COLOR: true
        DEBUG_COLORS: true
        ENV_FILE: ${{ inputs.env-file || steps.env.outputs.filename }}
      #language=bash
      run: |
        if [[ -n "$ENV_FILE" ]]; then
          source "$ENV_FILE" || echo "::warning::Failed to source env file"
        fi

        npx pdk-builder "$COMMAND" \
          --docker-command="$ROOT_COMMAND" \
          $ARGS
