name: 'Run PDK app builder'
description: 'Run @myparcel-pdk/app-builder'

inputs:
  command:
    description: 'Command to run'
    required: true

  image:
    description: 'PHP Docker image to use'
    required: false
    default: ''

  args:
    description: 'Additional arguments to pass to the command'
    required: false
    default: '-v'

runs:
  using: composite
  steps:
    - name: 'Create root command'
      id: prepare
      shell: bash
      env:
        IMAGE: ${{ inputs.image }}
      #language=bash
      run: |
        if [ -z "$IMAGE" ]; then
          ROOT_COMMAND=''
        else
          ROOT_COMMAND="docker run -t --user $(id -u):$(id -g) -v $PWD:/app -w /app $IMAGE"
        fi

        echo "root-command=$ROOT_COMMAND" >> $GITHUB_OUTPUT

    - shell: bash
      env:
        COMMAND: ${{ inputs.command }}
        ARGS: ${{ inputs.args }}
        PDK_ROOT_COMMAND: ${{ steps.prepare.outputs.root-command }}
      #language=bash
      run: |
        npx pdk-builder "$COMMAND" $ARGS --root-command="$PDK_ROOT_COMMAND"
