name: 'Build Docker image'
description: 'Build Docker image from cache using a registry'

inputs:
  image:
    description: 'Image name'
    required: false
    default: ${{ github.repository }}

  dockerfile:
    description: 'Path to dockerfile'
    required: false
    default: 'Dockerfile'

  context:
    description: 'Directory to build from'
    required: false
    default: '.'

  target:
    description: 'Target stage to build'
    required: false

  registry:
    description: 'Packages registry to use'
    required: false
    default: 'ghcr.io'

  registry-user:
    description: 'Username to log into registry with'
    required: false
    default: ${{ github.actor }}

  registry-password:
    description: 'Password to log into registry with'
    required: true

outputs:
  tagged-image:
    description: 'Created image name with tag'
    value: ${{ steps.build.outputs.tagged-image }}

runs:
  using: composite
  steps:
    - uses: myparcelnl/actions/deprecated@v4
      with:
        name: myparcelnl/actions/build-docker-image-reg
        replacement: myparcelnl/actions/build-docker-image

    - uses: myparcelnl/actions/build-docker-image@v4
      id: build
      with:
        image: ${{ inputs.image }}
        dockerfile: ${{ inputs.dockerfile }}
        context: ${{ inputs.context }}
        target: ${{ inputs.target }}
        registry: ${{ inputs.registry }}
        registry-user: ${{ inputs.registry-user }}
        registry-password: ${{ inputs.registry-password }}
