name: 'Update code coverage'
description: 'Update code coverage using codecov'

inputs:
  token:
    description: 'The codecov token for this repository'
    required: true

runs:
  using: composite
  steps:
    - uses: myparcelnl/actions/deprecated@v4
      with:
        name: 'myparcelnl/update-coverage'
        replacement: 'myparcelnl/codecov-action'

    - uses: myparcelnl/actions/codecov-action@v4
      with:
        token: ${{ inputs.token }}
