version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    commit-message:
      prefix: 'fix'
      prefix-development: 'build'
      include: 'scope'
    schedule:
      interval: 'daily'
