name: 'Run many nx actions'
description: 'Run multiple actions in parallel'

inputs:
  target:
    description: 'The target to run'
    required: true

  cloud:
    description: 'Whether this will run using nx cloud'
    required: false
    default: 'false'

  runner:
    description: 'The runner to use'
    required: false

  parallel:
    description: 'The number of parallel jobs to run'
    required: false
    default: ''

  args:
    description: 'The arguments to pass to the target'
    required: false

  prefix:
    description: 'The prefix to use for the commands'
    required: false
    default: 'npx'

  cache-dir:
    description: 'The nx cache directory'
    required: false
    default: '.nx/cache'

  max-cache-size:
    description: 'The maximum size of the cache in KB'
    required: false
    default: '8192'

runs:
  using: composite
  steps:
    - name: 'Prepare arguments'
      id: prepare
      env:
        PARALLEL: ${{ inputs.parallel }}
        ARGS: ${{ inputs.args }}
      shell: bash
      #language=bash
      run: |
        if [ -n "$PARALLEL" ]; then
          ARGS="--parallel=$PARALLEL $ARGS"
        fi

        echo "args=$ARGS"         >> $GITHUB_OUTPUT

    - uses: myparcelnl/actions/nx-run@v4
      with:
        command: 'run-many'
        args: ${{ steps.prepare.outputs.args }}
        cache-dir: ${{ inputs.cache-dir }}
        cloud: ${{ inputs.cloud }}
        max-cache-size: ${{ inputs.max-cache-size }}
        prefix: ${{ inputs.prefix }}
        runner: ${{ inputs.runner }}
        target: ${{ inputs.target }}
