name: 'Auto assign author'
description: 'Automatically assign the author of a pull request to the pull request.'

inputs:
  token:
    description: 'GitHub token to use. If passed, takes precedence over the `app-id` and `app-private-key` inputs.'

  app-id:
    description: 'The app ID of the app.'

  private-key:
    description: 'The private key of the app.'

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4

    - uses: myparcelnl/actions/get-github-token@v4
      id: token
      with:
        token: ${{ inputs.token }}
        app-id: ${{ inputs.app-id }}
        private-key: ${{ inputs.private-key }}

    - name: 'Assign author'
      uses: actions/github-script@v7
      if: steps.check.outputs.assignable == 'true'
      with:
        github-token: ${{ steps.token.outputs.token }}
        #language=javascript
        script: |
          if (context.payload.pull_request.assignees.length > 0) {
            console.log('Pull request already has assignees.');
            return;
          }

          const author = context.payload.pull_request.user.login;

          const permission = await github.rest.repos.getCollaboratorPermissionLevel({
            ...context.repo,
            username: author
          });

          if (permission.permission !== 'admin' && permission.permission !== 'write') {
            console.log(`Author "${author}" does not have the required permissions to be assigned.`);
            return;
          }

          github.rest.issues.addAssignees({
            ...context.repo,
            issue_number: context.payload.pull_request.number,
            assignees: [author]
          });

          console.log(`Assigned author "${author}" to pull request.`);
