name: 'Setup PDK'
description: 'Setup @myparcel-pdk/app-builder'

inputs:
  node-version:
    description: 'Node version to use'
    required: false

  yarn-args:
    description: 'Arguments to use with yarn install'
    required: false

  php-version:
    description: 'PHP version to use'
    default: '7.4'
    required: false

  composer-command:
    description: 'The composer command to run.'
    default: 'install'
    required: false

  composer-flags:
    description: 'Flags to use when installing composer dependencies.'
    required: false
    default: '--no-scripts --no-plugins --ignore-platform-req=ext-* --ignore-platform-req=lib-*'

outputs:
  image:
    description: 'The image name that was used to setup composer dependencies. Can be used in subsequent jobs.'
    value: ${{ steps.setup-backend.outputs.image }}

runs:
  using: composite
  steps:
    - uses: myparcelnl/actions/pdk-setup-backend@v4
      id: setup-backend
      with:
        composer-command: ${{ inputs.composer-command }}
        composer-flags: ${{ inputs.composer-flags }}
        php-version: ${{ inputs.php-version }}

    - uses: myparcelnl/actions/pdk-setup-frontend@v4
      with:
        node-version: ${{ inputs.node-version }}
        yarn-args: ${{ inputs.yarn-args }}
