name: 'Setup PDK'
description: 'Setup @myparcel-pdk/app-builder'

inputs:
  node-version:
    description: 'Node version to use'
    default: '20'
    required: false

  php-version:
    description: 'PHP version to use'
    default: '7.2'
    required: false

  root-command:
    description: 'Root command to use'
    required: false
    default: ''

  composer-flags:
    description: 'Flags to use when installing composer dependencies.'
    required: false
    default: ''

outputs:
  image:
    description: 'The image name that was used to setup composer dependencies. Can be used in subsequent jobs.'
    value: ${{ steps.composer.outputs.image }}

runs:
  using: composite
  steps:
    - uses: myparcelnl/actions/pdk-setup-backend@v4
      id: composer
      with:
        php-version: ${{ inputs.php-version }}
        composer-flags: ${{ inputs.composer-flags }}

    - uses: myparcelnl/actions/pdk-setup-frontend@v4
      with:
        node-version: ${{ inputs.node-version }}
        root-command: ${{ inputs.root-command }}
