name: 'Setup PDK'
description: 'Setup @myparcel-pdk/app-builder'

inputs:
  node-version:
    description: 'Node version to use'
    required: false

  yarn-args:
    description: 'Arguments to use with yarn install'
    required: false

runs:
  using: composite
  steps:
    - uses: myparcelnl/actions/yarn-install@v5
      with:
        yarn-args: ${{ inputs.yarn-args }}
        node-version: ${{ inputs.node-version }}

    - name: 'Check if nx is present'
      id: nx
      shell: bash
      #language=bash
      run: yarn nx --version
      continue-on-error: true

    - name: 'Set up nx cache'
      uses: myparcelnl/actions/nx-cache@v5
      if: steps.nx.outcome == 'success'

    - uses: myparcelnl/actions/pdk-builder@v5
      with:
        command: 'translations'
