name: 'Setup PDK'
description: 'Setup @myparcel-pdk/app-builder'

inputs:
  node-version:
    description: 'Node version to use'
    default: '20'
    required: false

  root-command:
    description: 'Root command to use'
    required: false
    default: ''

runs:
  using: composite
  steps:
    - uses: myparcelnl/actions/yarn-install@v4
      with:
        node-version: ${{ inputs.node-version }}

    - uses: myparcelnl/actions/pdk-builder@v4
      with:
        root-command: ${{ inputs.root-command }}
        command: 'translations'
