name: 'Run BundleWatch'
description: 'Check if the bundle size is within limits using BundleWatch'

inputs:
  config:
    description: 'The path to the BundleWatch config file'
    required: false
    default: ''

  token:
    description: 'The BundleWatch token'
    required: true

runs:
  using: composite
  steps:
    # The following was taken from:
    # https://github.com/woocommerce/google-listings-and-ads/blob/ba29fbec68cc156933a8bd9d866c45e89e821428/.github/workflows/bundle-size.yml#L41-L60
    - name: 'Prepare env values - push'
      if: ${{ github.event_name == 'push' }}
      shell: bash
      run: |
        BRANCH=$(echo '${{ github.event.ref }}' | sed 's/^refs\/heads\///')
        echo "CI_BRANCH=$BRANCH" >> $GITHUB_ENV
        echo "CI_BRANCH_BASE=$BRANCH" >> $GITHUB_ENV
        echo "CI_COMMIT_SHA=${{ github.sha }}" >> $GITHUB_ENV

    - name: 'Prepare env values - pull request'
      if: ${{ github.event_name == 'pull_request' }}
      shell: bash
      run: |
        echo "CI_BRANCH=${{ github.head_ref }}" >> $GITHUB_ENV
        echo "CI_BRANCH_BASE=${{ github.base_ref }}" >> $GITHUB_ENV
        echo "CI_COMMIT_SHA=${{ github.event.pull_request.head.sha }}" >> $GITHUB_ENV

    - name: 'Check bundle size'
      run: |
        npx bundlewatch $(if [ -n "${{ inputs.config }}" ]; then echo "--config ${{ inputs.config }}"; fi)
      shell: bash
      env:
        BUNDLEWATCH_GITHUB_TOKEN: ${{ inputs.token }}
