name: 'Create custom build'
description: 'Create custom build using specific PDK versions'

inputs:
  php-pdk-ref:
    default: 'main'
    description: 'Ref of myparcelnl/pdk to use'

  js-pdk-ref:
    default: 'main'
    description: 'Ref of myparcelnl/js-pdk to use'

  php-version:
    description: 'PHP version that is used'
    required: false
    default: '7.4'

  php-scoper-version:
    description: 'PHP Scoper Version'
    required: false
    default: '^0.18.0'

  source-files:
    description: 'List of source files to use for caching'
    required: true

  vendor-files:
    description: 'List of files to use for vendor caching'
    required: false
    default: |
      composer.json
      composer.lock
      scoper.inc.php
      scoper.*.inc.php

runs:
  using: composite
  steps:
    - name: 'Determine version'
      id: version
      shell: bash
      env:
        DEBUG: ${{ runner.debug }}
        RUN_ID: ${{ github.run_id }}
      #language=bash
      run: |
        version=$(npm pkg get version | sed 's/"//g')
        isPreRelease=$(echo "$version" | grep -E -- '-[a-z]+\.[0-9]+$' || true)

        if [ -n "$isPreRelease" ]; then
          releaseVersion="$version-$RUN_ID"
        else
          releaseVersion="$version-rc.$RUN_ID"
        fi

        if [ $DEBUG == "1" ]; then
          echo "RUN_ID=$RUN_ID"
          echo "isPreRelease=$isPreRelease"
          echo "releaseVersion=$releaseVersion"
          echo "version=$version"
        fi

        echo "version=$releaseVersion" >> $GITHUB_OUTPUT

    - name: 'Checkout myparcelnl/js-pdk'
      if: inputs.js-pdk-ref != 'main'
      uses: actions/checkout@v5
      with:
        path: js-pdk
        repository: myparcelnl/js-pdk
        ref: ${{ inputs.js-pdk-ref }}

    - name: 'Link myparcelnl/js-pdk'
      if: inputs.js-pdk-ref != 'main'
      shell: bash
      #language=bash
      run: |
        npm pkg set \
          "resolutions.@myparcel-dev/pdk-admin=portal:$GITHUB_WORKSPACE/js-pdk/apps/admin" \
          "resolutions.@myparcel-dev/pdk-admin-component-tests=portal:$GITHUB_WORKSPACE/js-pdk/apps/admin-component-tests" \
          "resolutions.@myparcel-dev/pdk-admin-js=portal:$GITHUB_WORKSPACE/js-pdk/apps/admin-js" \
          "resolutions.@myparcel-dev/pdk-admin-preset-bootstrap4=portal:$GITHUB_WORKSPACE/js-pdk/apps/admin-preset-bootstrap4" \
          "resolutions.@myparcel-dev/pdk-admin-preset-dashicons=portal:$GITHUB_WORKSPACE/js-pdk/apps/admin-preset-dashicons" \
          "resolutions.@myparcel-dev/pdk-admin-preset-default=portal:$GITHUB_WORKSPACE/js-pdk/apps/admin-preset-default" \
          "resolutions.@myparcel-dev/pdk-admin-preset-fontawesome=portal:$GITHUB_WORKSPACE/js-pdk/apps/admin-preset-fontawesome" \
          "resolutions.@myparcel-dev/pdk-checkout=portal:$GITHUB_WORKSPACE/js-pdk/apps/checkout" \
          "resolutions.@myparcel-dev/pdk-checkout-js=portal:$GITHUB_WORKSPACE/js-pdk/apps/checkout-js" \
          "resolutions.@myparcel-dev/pdk-checkout-common=portal:$GITHUB_WORKSPACE/js-pdk/libs/checkout-common" \
          "resolutions.@myparcel-dev/pdk-checkout-delivery-options=portal:$GITHUB_WORKSPACE/js-pdk/libs/checkout-delivery-options" \
          "resolutions.@myparcel-dev/pdk-checkout-separate-address-fields=portal:$GITHUB_WORKSPACE/js-pdk/libs/checkout-separate-address-fields" \
          "resolutions.@myparcel-dev/pdk-checkout-tax-fields=portal:$GITHUB_WORKSPACE/js-pdk/libs/checkout-tax-fields" \
          "resolutions.@myparcel-dev/pdk-common=portal:$GITHUB_WORKSPACE/js-pdk/libs/common"

    - name: 'Link myparcelnl/pdk'
      if: inputs.php-pdk-ref != 'main'
      env:
        REF: ${{ inputs.php-pdk-ref }}
      shell: bash
      #language=bash
      run: |
        jq '.require["myparcelnl/pdk"] = "dev-'$REF'" | ."minimum-stability" = "dev"' composer.json > composer.json.tmp
        mv composer.json.tmp composer.json

    - uses: myparcelnl/actions/pdk-setup@v5
      id: setup
      with:
        composer-command: 'update'
        composer-dev: false
        php-version: ${{ inputs.php-version }}
        yarn-args: '--no-immutable'

    - uses: myparcelnl/actions/pdk-cache@v5
      with:
        php-version: ${{ inputs.php-version }}
        php-scoper-version: ${{ inputs.php-scoper-version }}
        source-files: ${{ inputs.source-files }}
        vendor-files: ${{ inputs.vendor-files }}
        vendor-key: update-${{ steps.setup.outputs.composer-flags }}

    - uses: myparcelnl/actions/pdk-release@v5
      with:
        command: 'prerelease'
        image: ${{ steps.setup.outputs.image }}
        version: ${{ steps.version.outputs.version }}

    - name: 'Write summary'
      shell: bash
      env:
        JS_PDK_REF: ${{ inputs.js-pdk-ref }}
        PHP_PDK_REF: ${{ inputs.php-pdk-ref }}
        VERSION: ${{ steps.version.outputs.version }}
        SERVER_URL: ${{ github.server_url }}
      #language=bash
      run: |
        echo "# Build summary"                                                                            >> $GITHUB_STEP_SUMMARY
        echo ""                                                                                           >> $GITHUB_STEP_SUMMARY
        echo "- **Generated version**: $VERSION"                                                          >> $GITHUB_STEP_SUMMARY
        echo "- **myparcelnl/pdk**: [$PHP_PDK_REF]($SERVER_URL/myparcelnl/pdk/commits/$PHP_PDK_REF/)"     >> $GITHUB_STEP_SUMMARY
        echo "- **myparcelnl/js-pdk**: [$JS_PDK_REF]($SERVER_URL/myparcelnl/js-pdk/commits/$JS_PDK_REF/)" >> $GITHUB_STEP_SUMMARY
