name: 'Install npm dependencies'
description: 'Install npm dependencies from scratch or from cache'

inputs:
  node-version:
    description: 'The Node.js version to use'
    default: '20'
    required: false

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'

    - name: 'Install npm dependencies'
      shell: bash
      #language=bash
      run: npm ci
