name: Install npm dependencies
description: Install npm dependencies from scratch or from cache

inputs:
  node-version:
    description: 'The Node.js version to use'
    default: '14'
    required: false

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ inputs.node-version }}

    - name: Prepare npm cache
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install npm dependencies
      run: npm ci
      shell: bash
