name: Install npm dependencies
description: Install npm dependencies from scratch or from cache

inputs:
  node-version:
    description: 'The Node.js version to use'
    default: '18'
    required: false

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'

    - name: 'Install npm dependencies'
      run: npm ci
      shell: bash
