name: 'Setup Node'
description: 'Setup Node'

inputs:
  node-version:
    description: 'The Node.js version to use'
    default: '16'
    required: false

runs:
  using: composite
  steps:
    - name: 'Setup Node'
      uses: actions/setup-node@v2
      with:
        node-version: ${{ inputs.node-version }}
