name: 'Create PR prerelease artifacts'
description: 'Requires package to have been built'

inputs:
  pr-number:
    description: 'Pull request number'
    required: true

  image:
    description: 'PHP Docker image to use'
    required: true

outputs:
  version:
    description: 'The version that was released.'
    value: ${{ steps.version.outputs.version }}

runs:
  using: composite
  steps:
    - name: 'Determine version'
      id: version
      shell: bash
      env:
        PR_NUMBER: ${{ inputs.pr-number }}
      #language=bash
      run: |
        version=$(npm pkg get version | sed 's/"//g') 
        releaseVersion="$version-$PR_NUMBER"

        echo "version=$releaseVersion" >> $GITHUB_OUTPUT

    - uses: myparcelnl/actions/pdk-upgrade@v4
      with:
        no-commit: true
        image: ${{ inputs.image }}

    - uses: myparcelnl/actions/pdk-release@v4
      with:
        command: 'prerelease'
        image: ${{ inputs.image }}
        version: ${{ steps.version.outputs.version }}
