name: 'Setup Git credentials'
description: 'Authenticates Git as MyParcelBot.'

inputs:
  token:
    required: true
    description: 'GitHub Personal access token'

runs:
  using: composite
  steps:
    - uses: oleksiyrudenko/gha-git-credentials@ac5b66bcf3873df4259c681d957d8c145980171f
      with:
        token: ${{ inputs.token }}
        name: 'MyParcelBot'
        email: 'edie+bot@myparcel.nl'
        actor: 'MyParcelBot'
