name: 'Run many nx actions'
description: 'Run multiple actions in parallel'

inputs:
  target:
    description: 'The target to run'
    required: true

  args:
    description: 'The arguments to pass to the target'
    required: false
    default: ''

  prefix:
    description: 'The prefix to use for the commands'
    required: false
    default: 'npx'

  cache-dir:
    description: 'The nx cache directory'
    required: false
    default: '.nx/cache'

  max-cache-size:
    description: 'The maximum size of the cache in KB'
    required: false
    default: '8192'

runs:
  using: composite
  steps:
    - uses: myparcelnl/actions/nx-cache@v4
      with:
        cache-dir: ${{ inputs.cache-dir }}
        max-cache-size: ${{ inputs.max-cache-size }}

    - name: 'Run'
      shell: bash
      env:
        NX_CACHE_DIRECTORY: ${{ inputs.cache-dir }}
        NX_REJECT_UNKNOWN_LOCAL_CACHE: '0'
      #language=bash
      run: |
        ${{ inputs.prefix }} nx run ${{ inputs.target }} \
          --output-style=static \
          ${{ inputs.args }}
