name: 'Run Pest'
description: 'Requires Docker image to be set up'

inputs:
  image:
    description: 'PHP Docker image to use'
    required: false

  php-version:
    description: 'PHP version to use. If image is set, this will be ignored.'
    default: '7.4'
    required: false

  php-args:
    description: 'Arguments to pass to PHP. Should be a multiline string.'
    required: false

  pest-args:
    description: 'Arguments to pass to Pest. Should be a multiline string.'
    required: false

  # deprecated, use pest-args
  # TODO: Remove in v5
  args:
    description: 'Arguments to pass to Pest. Should be a multiline string.'
    required: false

runs:
  using: composite
  steps:
    - uses: myparcelnl/actions/deprecated@v4
      if: inputs.args != ''
      with:
        name: 'inputs.args'
        replacement: 'inputs.pest-args'
        reason: 'To prevent confusion with inputs.php-args.'

    - uses: myparcelnl/actions/composer-install@v4
      id: install
      if: inputs.image == ''
      with:
        php-version: ${{ inputs.php-version }}

    - uses: myparcelnl/actions/composer-create-env-file@v4
      id: env

    - uses: myparcelnl/actions/format-string@v4
      id: php-args
      with:
        mode: 'args'
        string: |
          -dpcov.enabled=1
          ${{ inputs.php-args }}

    - uses: myparcelnl/actions/format-string@v4
      id: pest-args
      with:
        mode: 'args'
        string: |
          --no-interaction
          --colors=always
          --coverage-clover=clover.xml
          --log-junit=junit.xml
          ${{ inputs.pest-args || inputs.args }}

    - name: 'Run Pest'
      env:
        ENV_FILE: ${{ steps.env.outputs.filename }}
        IMAGE: ${{ inputs.image || steps.install.outputs.image }}
        PEST_ARGS: ${{ steps.pest-args.outputs.string }}
        PHP_ARGS: ${{ steps.php-args.outputs.string }}
        TERM: xterm-256color
      shell: bash
      #language=bash
      run: |
        docker run -t \
          --env-file="$ENV_FILE" \
          --user $(id -u):$(id -g) \
          --volume "$PWD:/app" \
          "$IMAGE" \
          php $PHP_ARGS vendor/bin/pest $PEST_ARGS
