name: 'Semantic release'
description: 'Run semantic release using the MyParcel bot'

inputs:
  token:
    description: 'GitHub Personal access token'
    required: true

outputs:
  version:
    description: 'The new version'
    value: ${{ steps.release.outputs.version }}

  previous-version:
    description: 'The previous version'
    value: ${{ steps.release.outputs.previous-version }}

  released:
    description: 'Whether a new version was released'
    value: ${{ steps.release.outputs.released }}

runs:
  using: composite
  steps:
    - uses: myparcelnl/actions/setup-git-credentials@main
      with:
        token: ${{ inputs.token }}

    - name: 'Fetch tags'
      run: |
        git fetch --tags
      shell: bash

    - name: 'Get previous version'
      run: |
        tag=$(git describe --tags --abbrev=0)
        echo "::set-output name=previous-version::${tag}"
      id: previous-version
      shell: bash

    - name: 'Run semantic release'
      run: npx semantic-release
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.token }}

    - name: 'Get new version'
      run: |
        tag=$(git describe --tags --abbrev=0)
        echo "::set-output name=version::${tag}"
      id: version
      shell: bash

    - name: 'Update outputs'
      run: |
        if [ "${{ steps.previous-version.outputs.previous-version }}" == "${{ steps.version.outputs.version }}" ]; then
          echo "::set-output name=released::false"
          echo "::set-output name=version::"
        else
          echo "::set-output name=released::true"
        fi
      shell: bash
