name: 'Semantic release'
description: 'Run semantic release using the MyParcel bot'

inputs:
  token:
    description: 'GitHub Personal access token'
    required: true

runs:
  using: composite
  steps:
    - uses: myparcelnl/actions/setup-git-credentials@main
      with:
        token: ${{ inputs.token }}

    - name: 'Run semantic release'
      run: npx semantic-release
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
