name: 'Semantic release'
description: 'Run semantic release using the MyParcel bot'

inputs:
  token:
    description: 'GitHub token'
    required: true

runs:
  using: composite
  steps:
    - name: 'Run semantic release'
      run: npx semantic-release
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
        GIT_AUTHOR_NAME: MyParcelBot
        GIT_AUTHOR_EMAIL: edie+bot@myparcel.nl
        GIT_COMMITTER_NAME: MyParcelBot
        GIT_COMMITTER_EMAIL: edie+bot@myparcel.nl
