name: 'Install yarn dependencies'
description: 'Install yarn dependencies using cache'

inputs:
  node-version:
    description: 'The Node.js version to use'
    default: '18'
    required: false

  yarn-args:
    description: 'Arguments to use with yarn install'
    required: false

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'yarn'

    - name: 'Create variables'
      id: variables
      shell: bash
      run: |
        version=$(yarn --version | cut -d. -f1)

        if [ "$version" -lt "2" ]; then
          echo "args=--frozen-lockfile"
        fi

    - name: 'Install yarn dependencies'
      shell: bash
      run: |
        yarn install ${{ steps.variables.outputs.args }} ${{ inputs.yarn-args }}
      env:
        YARN_ENABLE_GLOBAL_CACHE: 'false'
        YARN_NM_MODE: 'hardlinks-local'
        HUSKY: '0'
