name: 'Mark as deprecated'
description: 'Mark something as deprecated'

inputs:
  name:
    description: 'Name of the thing to mark as deprecated'
    required: true

  replacement:
    description: 'The replacement'
    required: false

  reason:
    description: 'The reason why it is deprecated'
    required: false

runs:
  using: composite
  steps:
    - name: 'Report deprecation'
      shell: bash
      env:
        NAME: ${{ inputs.name }}
        REPLACEMENT: ${{ inputs.replacement }}
        REASON: ${{ inputs.reason }}
      #language=bash
      run: |
        message="$NAME is deprecated and will be removed in the next major version."

        if [ -n "$REPLACEMENT" ]; then
          message="${message} Use $REPLACEMENT instead."
        fi

        if [ -n "$REASON" ]; then
          message="${message} Reason: $REASON"
        fi

        echo "::warning::$message"
