name: 'Install composer dependencies'
description: 'Set up PHP and install composer dependencies'

inputs:
  command:
    description: 'The composer command to run.'
    required: false
    default: 'install'

  flags:
    description: 'Flags to use when installing composer dependencies.'
    required: false
    default: '--no-scripts --no-plugins'

  php-version:
    description: 'The php version to use.'
    default: '7.2'
    required: false

outputs:
  image:
    description: 'The image name that was used to install dependencies. Can be used in subsequent jobs.'
    value: ${{ steps.prepare.outputs.image }}

runs:
  using: composite
  steps:
    - name: 'Get image name'
      id: prepare
      shell: bash
      run: |
        echo "image=ghcr.io/myparcelnl/php-xd:${{ inputs.php-version }}-cli-alpine" >> $GITHUB_OUTPUT

    - name: 'Handle composer cache'
      uses: actions/cache@v4
      with:
        path: /tmp/composer-cache
        key: composer-${{ hashFiles('**/composer.json, **/composer.lock') }}
        restore-keys: |
          composer-

    - name: 'Handle vendor folder cache'
      uses: actions/cache@v4
      with:
        path: vendor
        key: composer-vendor-${{ hashFiles('**/composer.json', '**/composer.lock') }}-${{ inputs.flags }}
        restore-keys: |
          composer-vendor-${{ hashFiles('**/composer.json', '**/composer.lock') }}-
          composer-vendor-

    - uses: myparcelnl/actions/pull-docker-image@v4
      with:
        image: ${{ steps.prepare.outputs.image }}

    - name: 'Install composer dependencies'
      shell: bash
      run: |
        docker run \
          --volume /tmp/composer-cache:/root/.composer \
          --volume $PWD:/app \
          --env COMPOSER_CACHE_DIR=/root/.composer \
          ${{ steps.prepare.outputs.image }} \
          composer ${{ inputs.command }} --no-interaction --no-progress ${{ inputs.flags }}
