name: 'Set up PHP'
description: 'Set up PHP and install composer dependencies from scratch or from cache'

inputs:
  php-version:
    description: 'The php version to use.'
    default: '7.2'
    required: false

  flags:
    description: 'Flags to use when installing composer dependencies.'
    required: false
    default: ''

outputs:
  image:
    description: 'The image name that was used to install dependencies. Can be used in subsequent jobs.'
    value: ${{ steps.prepare.outputs.image }}

runs:
  using: composite
  steps:
    - name: 'Get image name'
      id: prepare
      shell: bash
      run: |
        echo "image=ghcr.io/myparcelnl/php-xd:${{ inputs.php-version }}-cli-alpine" >> $GITHUB_OUTPUT

    - name: 'Handle composer cache'
      uses: actions/cache@v3
      with:
        path: $HOME/.composer
        key: composer-${{ hashFiles('**/composer.json') }}-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          composer-${{ hashFiles('**/composer.json') }}-
          composer-

    - uses: myparcelnl/actions/pull-docker-image@v3
      with:
        image: ${{ steps.prepare.outputs.image }}

    - name: 'Install composer dependencies'
      shell: bash
      run: |
        docker run \
          --volume $HOME/.composer:/root/.composer \
          --volume $PWD:/app \
          --env COMPOSER_CACHE_DIR=/root/.composer \
          ${{ steps.prepare.outputs.image }} \
          composer install --no-interaction --no-progress ${{ inputs.flags }}
