name: 'Set up PHP'
description: 'Set up PHP and install composer dependencies from scratch or from cache'

inputs:
  php-version:
    description: 'The php version to use.'
    default: '7.2'
    required: false

  flags:
    description: 'Flags to use when installing composer dependencies.'
    required: false
    default: ''

runs:
  using: composite
  steps:
    - name: 'Handle composer cache'
      uses: actions/cache@v3
      with:
        path: $HOME/.composer
        key: composer-${{ hashFiles('**/composer.json') }}-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          composer-${{ hashFiles('**/composer.json') }}-
          composer-

    - uses: myparcelnl/actions/pull-docker-image@v3
      with:
        image: ghcr.io/myparcelnl/php-xd:${{ inputs.php-version }}-cli-alpine

    - name: 'Install composer dependencies'
      shell: bash
      run: |
        docker compose run \
          --volume $HOME/.composer:/root/.composer \
          --env COMPOSER_CACHE_DIR=/root/.composer \
          php \
          composer install --no-interaction --no-progress ${{ inputs.flags }}
