name: 'Install composer dependencies'
description: 'Set up PHP and install composer dependencies'

inputs:
  command:
    description: 'The composer command to run.'
    required: false
    default: 'install'

  flags:
    description: 'Flags to use when installing composer dependencies.'
    required: false
    default: '--no-scripts --no-plugins'

  php-version:
    description: 'The php version to use.'
    default: '7.2'
    required: false

outputs:
  image:
    description: 'The image name that was used to install dependencies. Can be used in subsequent jobs.'
    value: ${{ steps.prepare.outputs.image }}

runs:
  using: composite
  steps:
    - name: 'Get image name'
      id: prepare
      shell: bash
      env:
        VERSION: ${{ inputs.php-version }}
      #language=bash
      run: |
        echo "image=ghcr.io/myparcelnl/php-xd:$VERSION-cli-alpine" >> $GITHUB_OUTPUT

    - name: 'Handle composer cache'
      uses: actions/cache@v4
      with:
        path: /tmp/composer-cache
        key: composer-${{ inputs.php-version }}-${{ inputs.command }}-${{ inputs.flags }}-${{ hashFiles('**/composer.json', '**/composer.lock') }}
        restore-keys: |
          composer-${{ inputs.php-version }}-${{ inputs.command }}-${{ inputs.flags }}-
          composer-${{ inputs.php-version }}-${{ inputs.command }}-
          composer-${{ inputs.php-version }}-

    - name: 'Handle vendor folder cache'
      uses: actions/cache@v4
      with:
        path: vendor
        key: composer-vendor-${{ inputs.php-version }}-${{ inputs.command}}-${{ inputs.flags }}-${{ hashFiles('**/composer.json', '**/composer.lock') }}
        restore-keys: |
          composer-vendor-${{ inputs.php-version }}-${{ inputs.command}}-${{ inputs.flags }}-
          composer-vendor-${{ inputs.php-version }}-${{ inputs.command}}-
          composer-vendor-${{ inputs.php-version }}-

    - uses: myparcelnl/actions/pull-docker-image@v4
      with:
        image: ${{ steps.prepare.outputs.image }}

    - name: 'Install composer dependencies'
      shell: bash
      env:
        IMAGE: ${{ steps.prepare.outputs.image }}
        COMMAND: ${{ inputs.command }}
        FLAGS: ${{ inputs.flags }}
      #language=bash
      run: |
        docker run \
          --env COMPOSER_CACHE_DIR=/root/.composer \
          --user $(id -u):$(id -g) \
          --volume $PWD:/app \
          --volume /tmp/composer-cache:/root/.composer \
          "$IMAGE" \
          composer $COMMAND --no-interaction --no-progress $FLAGS
