name: 'Sync files to S3'
description: 'Sync files to S3 and invalidate CloudFront'

inputs:
  source:
    description: 'Path to the folder to sync.'
    required: true

  bucket:
    description: 'Name of the S3 bucket to sync to.'
    required: true

  delete:
    description: 'Delete files that exist in the destination but not in the source during sync.'
    required: false

  distribution-id:
    description: 'The CloudFront distribution id. If provided, the distribution will be invalidated after the sync.'
    required: false

runs:
  using: composite
  steps:
    - name: 'Sync files'
      shell: bash
      run: |
        aws s3 sync "${{ inputs.source }}" \
          "s3://${{ inputs.bucket }}" \
          ${{ inputs.delete && '--delete' }}

    - name: 'Invalidate CloudFront'
      if: inputs.distribution-id != ''
      shell: bash
      run: |
        aws cloudfront create-invalidation \
          --distribution-id ${{ inputs.distribution-id }} \
          --paths "/*"
