name: 'Cache PDK data'
description: 'Cache data used with @myparcel-pdk/app-builder'

inputs:
  php-version:
    description: 'PHP version that is used'
    required: false
    default: '7.4'

  php-scoper-version:
    description: 'PHP Scoper Version'
    required: false
    default: '^0.18.0'

  vendor-key:
    description: 'Composer key to use for caching in addition to the vendor files. For example the arguments used in composer install.'
    required: false

  source-files:
    description: 'List of files to use for source caching'
    required: true

  vendor-files:
    description: 'List of files to use for vendor caching'
    required: false
    default: |
      **/composer.json
      **/composer.lock
      **/scoper.inc.php
      **/scoper.*.inc.php

runs:
  using: composite
  steps:
    - uses: myparcelnl/actions/hash-string@v4
      id: vendor-key
      with:
        string: ${{ inputs.vendor-key }}

    - name: 'Create hashes'
      id: hashes
      uses: actions/github-script@v7
      env:
        SOURCE_FILES: ${{ inputs.source-files }}
        VENDOR_FILES: ${{ inputs.vendor-files }}
        VENDOR_KEY_HASH: ${{ steps.vendor-key.outputs.hash }}
      with:
        #language=js
        script: |
          const sourceFiles = process.env.SOURCE_FILES.trim().split('\n')
          const vendorFiles = process.env.VENDOR_FILES.trim().split('\n')

          const sourceHash = await glob.hashFiles(...sourceFiles);
          const vendorHash = await glob.hashFiles(...vendorFiles);

          core.setOutput('source-hash', sourceHash);
          core.setOutput('vendor-hash', [vendorHash, process.env.VENDOR_KEY_HASH].filter(Boolean).join('-'));

    - name: 'Cache php-scoper'
      uses: actions/cache@v4
      with:
        path: .tmp/php-scoper
        key: php-scoper-${{ inputs.php-version }}-${{ inputs.php-scoper-version }}

    - name: 'Cache scoped source php'
      uses: actions/cache@v4
      with:
        path: .tmp/scoped/source
        key: scoped-php-src-${{ inputs.php-version }}-${{ steps.hashes.outputs.source-hash }}

    - name: 'Cache scoped vendor php'
      uses: actions/cache@v4
      with:
        path: .tmp/scoped/vendor
        key: scoped-php-vendor-${{ inputs.php-version }}-${{ steps.hashes.outputs.vendor-hash }}
