name: 'Install yarn 2 dependencies'
description: 'Install yarn 2 dependencies from scratch or from cache'

inputs:
  node-version:
    description: 'The Node.js version to use'
    default: '16'
    required: false

  yarn-args:
    description: 'Arguments to use with yarn install'
    default: ''
    required: false

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'yarn'

    - name: 'Install yarn dependencies'
      run: yarn install ${{ inputs.yarn-args }}
      shell: bash
