name: 'Install yarn 2 dependencies'
description: 'Install yarn 2 dependencies from scratch or from cache'

inputs:
  node-version:
    description: 'The Node.js version to use'
    default: '18'
    required: false

  yarn-args:
    description: 'Arguments to use with yarn install'
    default: ''
    required: false

runs:
  using: composite
  steps:
    - name: 'Notify about deprecation'
      shell: bash
      run: |
        echo "::warning::myparcelnl/actions/yarn2-install is deprecated. Please switch to myparcelnl/actions/yarn-install. This action will be removed in v4."

    - uses: ./yarn-install
      with:
        node-version: ${{ inputs.node-version }}
        yarn-args: ${{ inputs.yarn-args }}
