name: Install yarn 2 dependencies
description: Install yarn 2 dependencies from scratch or from cache

inputs:
  node-version:
    description: 'The Node.js version to use'
    default: '16'
    required: false

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}

    - name: 'Get yarn cache directory path'
      id: yarn-cache-dir-path
      shell: bash
      run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

    - uses: actions/cache@v3
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: 'Install yarn dependencies'
      run: yarn install
      shell: bash
