name: 'Install pnpm dependencies'
description: 'Install pnpm dependencies from scratch or from cache'

inputs:
  node-version:
    description: 'The Node.js version to use'
    required: false

  pnpm-version:
    description: 'The pnpm version to use'
    default: '8.15.1'
    required: false

  pnpm-args:
    description: 'Arguments to use with pnpm install'
    default: '--frozen-lockfile'
    required: false

runs:
  using: composite
  steps:
    # TODO: REMOVE THIS!
    - uses: actions/checkout@v4

    - name: 'Enable corepack'
      shell: bash
      #language=bash
      run: |
        corepack enable

    - uses: myparcelnl/actions/setup-node@v4
      with:
        cache: 'pnpm'
        key: 'pnpm'
        node-version: ${{ inputs.node-version }}

    - name: 'Install pnpm dependencies'
      shell: bash
      #language=bash
      run: pnpm install ${{ inputs.pnpm-args }}
