name: 'Install pnpm dependencies'
description: 'Install pnpm dependencies from scratch or from cache'

inputs:
  node-version:
    description: 'The Node.js version to use'
    default: '20'
    required: false

  pnpm-version:
    description: 'The pnpm version to use'
    default: '8.15.1'
    required: false

  pnpm-args:
    description: 'Arguments to use with pnpm install'
    default: '--frozen-lockfile'
    required: false

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4

    - uses: pnpm/action-setup@v2.4.0
      with:
        version: ${{ inputs.pnpm-version }}
        run_install: false

    - uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'pnpm'

    - name: 'Install pnpm dependencies'
      shell: bash
      run: pnpm install ${{ inputs.pnpm-args }}
