name: 'Install pnpm dependencies'
description: 'Install pnpm dependencies from scratch or from cache'

inputs:
  node-version:
    description: 'The Node.js version to use'
    required: false

  pnpm-args:
    description: 'Arguments to use with pnpm install. Can be multiline string.'
    required: false

runs:
  using: composite
  steps:
    - name: 'Enable corepack'
      shell: bash
      #language=bash
      run: |
        corepack enable

    - uses: myparcelnl/actions/setup-node@v4
      with:
        cache: 'pnpm'
        key: 'pnpm'
        node-version: ${{ inputs.node-version }}

    - uses: myparcelnl/actions/format-string@v4
      id: args
      with:
        mode: 'args'
        string: |
          --frozen-lockfile
          ${{ inputs.pnpm-args }}

    - name: 'Install pnpm dependencies'
      shell: bash
      env:
        ARGS: ${{ steps.args.outputs.string }}
      #language=bash
      run: pnpm install $ARGS
