name: 'Run Behat'
description: 'Requires Docker image to be set up'

inputs:
  image:
    description: 'PHP Docker image to use'
    required: false
    default: ''

  php-version:
    description: 'PHP version to use. If image is set, this will be ignored.'
    default: '7.4'
    required: false

  args:
    description: 'Arguments to pass to Behat. Can be multiline string.'
    required: false
    default: ''

runs:
  using: composite
  steps:
    - uses: myparcelnl/actions/composer-install@v4
      id: install
      if: ${{ inputs.image == '' }}
      with:
        php-version: ${{ inputs.php-version }}

    - uses: myparcelnl/actions/composer-create-env-file@v4
      id: env

    - uses: myparcelnl/actions/format-string@v4
      id: args
      with:
        mode: 'args'
        string: ${{ inputs.args }}

    - name: 'Run Behat'
      env:
        ARGS: ${{ steps.args.outputs.string }}
        ENV_FILE: ${{ steps.env.outputs.filename }}
        IMAGE: ${{ inputs.image || steps.install.outputs.image }}
      shell: bash
      #language=bash
      run: |
        docker run -t \
          --env-file="$ENV_FILE" \
          --user $(id -u):$(id -g) \
          --volume $PWD:/app \
          "$IMAGE" \
          php \
            vendor/bin/behat $ARGS \
            --colors \
            --no-interaction
