name: 'Cache Nx'
description: 'Cache Nx build results'

outputs:
  cache-hit:
    description: 'A boolean value to indicate an exact match was found for the primary key'
    value: ${{ steps.cache.outputs.cache-hit}}

runs:
  using: composite
  steps:
    - name: 'Cache Nx'
      uses: actions/cache@v4
      id: cache
      with:
        path: |
          node_modules/.cache/nx
          .nx
        key: ${{ runner.os }}-nx-cache-${{ hashFiles('nx.json', '**/project.json') }}
        restore-keys: |
          ${{ runner.os }}-nx-cache-
