name: 'Cache Nx'
description: 'Cache Nx build results'

inputs:
  cache-dir:
    description: 'The nx cache directory'
    required: false
    default: '.nx/cache'

  max-cache-size:
    description: 'The maximum size of the cache in KB'
    required: false
    default: '8192'

outputs:
  cache-hit:
    description: 'A boolean value to indicate an exact match was found for the primary key'
    value: ${{ steps.cache.outputs.cache-hit}}

  cache-primary-key:
    description: 'A resolved cache key for which cache match was attempted'
    value: ${{ steps.cache.outputs.cache-primary-key }}

  cache-matched-key:
    description: 'Key of the cache that was restored, it could either be the primary key on cache-hit or a partial/complete match of one of the restore keys'
    value: ${{ steps.cache.outputs.cache-matched-key }}

runs:
  using: composite
  steps:
    - name: 'Restore nx cache'
      id: cache
      uses: actions/cache/restore@v4
      with:
        path: ${{ inputs.cache-dir }}
        key: '${{ runner.os }}-nx-cache-${{ github.sha }}-${{ github.run_id }}-${{ github.run_number }}'
        restore-keys: |
          ${{ runner.os }}-nx-cache-${{ github.sha }}-${{ github.run_id }}-
          ${{ runner.os }}-nx-cache-${{ github.sha }}-

    - name: 'Prune cache'
      if: steps.cache.outputs.cache-hit == 'true'
      env:
        MAX_CACHE_SIZE: ${{ inputs.max-cache-size }}
        NX_CACHE_DIRECTORY: ${{ inputs.cache-dir }}
      shell: bash
      #language=bash
      run: |
        maxSizeKB=$(($MAX_CACHE_SIZE))
        cacheDir="$NX_CACHE_DIRECTORY"

        function size() {
          (du -sk "$1" 2>/dev/null || echo 0) | cut -f 1
        }

        # Sort files by modification time, oldest first
        taskHashes=$(ls -trF "$cacheDir" 2>/dev/null || echo "" | grep "\d\+/$" | sed 's/\///')

        # Calculate current total size
        totalSize=0

        for hash in "${taskHashes[@]}"; do
          totalSize=$((totalSize + $(size "$cacheDir/$hash")))

          if [ -f "$cacheDir/$hash.commit" ]; then
            totalSize=$((totalSize + $(size "$cacheDir/$hash.commit")))
          fi

          if [ -f "$cacheDir/terminalOutputs/$hash" ]; then
            totalSize=$((totalSize + $(size "$cacheDir/terminalOutputs/$hash")))
          fi
        done

        if [ "$totalSize" -le "$maxSizeKB" ]; then
          echo "Cache size is already below the threshold."
          exit 0
        fi

        startSize=$totalSize

        echo "Starting total size: $startSize KB, requested max size: $maxSizeKB KB"

        i=0

        # Delete oldest files until the total size is below the threshold
        while [ "$totalSize" -gt "$maxSizeKB" ]; do
          hash=${taskHashes[$i]}

          if [ "$hash" == "" ]; then
            break
          fi

          totalSize=$((totalSize - $(size "$cacheDir/$hash")))
          totalSize=$((totalSize - $(size "$cacheDir/$hash.commit")))
          totalSize=$((totalSize - $(size "$cacheDir/terminalOutputs/$hash")))

          rm -rf "$cacheDir/$hash"
          rm -f  "$cacheDir/$hash.commit"
          rm -f  "$cacheDir/terminalOutputs/$hash"

          echo "Deleted files associated with hash $hash; Total size is now $totalSize KB."
          i=$((i + 1))
        done

        echo "Pruned cache from $startSize KB to $totalSize KB by deleting $i items."
