name: 'Update composer dependencies'
description: 'Set up PHP and update composer dependencies'

inputs:
  php-version:
    description: 'The php version to use.'
    default: '7.2'
    required: false

  composer-args:
    description: 'Arguments to pass to Composer. Should be a multiline string.'
    required: false

  # Deprecated, use composer-args
  # TODO: Remove in v5
  flags:
    description: 'Flags to use when installing composer dependencies.'
    required: false

outputs:
  image:
    description: 'The image name that was used to install dependencies. Can be used in subsequent jobs.'
    value: ${{ steps.install.outputs.image }}

  env-file:
    description: 'The filename of the env file that was created.'
    value: ${{ steps.install.outputs.env-file }}

runs:
  using: composite
  steps:
    - uses: myparcelnl/actions/deprecated@v4
      if: inputs.flags != ''
      with:
        name: 'inputs.flags'
        replacement: 'inputs.composer-args'

    - uses: myparcelnl/actions/composer-install@v4
      id: install
      with:
        command: 'update'
        composer-args: ${{ inputs.composer-args || inputs.flags }}
        php-version: ${{ inputs.php-version }}
