name: 'Update composer dependencies'
description: 'Set up PHP and update composer dependencies'

inputs:
  flags:
    description: 'Flags to use when installing composer dependencies.'
    required: false
    default: '--no-scripts --no-plugins'

  php-version:
    description: 'The php version to use.'
    default: '7.2'
    required: false

outputs:
  image:
    description: 'The image name that was used to install dependencies. Can be used in subsequent jobs.'
    value: ${{ steps.install.outputs.image }}

  env-file:
    description: 'The filename of the env file that was created.'
    value: ${{ steps.install.outputs.env-file }}

runs:
  using: composite
  steps:
    - uses: myparcelnl/actions/composer-install@v4
      id: install
      with:
        command: 'update'
        flags: ${{ inputs.flags }}
        php-version: ${{ inputs.php-version }}
