name: 'Rebase'
description: 'Rebase and update one branch with another.'

inputs:
  target:
    description: 'Target branch you wish to update.'
    required: true

  base:
    description: 'Base branch to use to rebase target.'
    required: true

  token:
    description: 'GitHub token to use.'
    required: true

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ inputs.token }}
        ref: ${{ inputs.target }}
        fetch-depth: 0

    - uses: myparcelnl/actions/setup-git-credentials@main
      with:
        token: ${{ inputs.token }}

    - name: 'Rebase and push'
      shell: bash
      run: |
        git rebase "origin/${{ inputs.base }}"
        git push
