name: 'Rebase'
description: 'Rebase and update one branch with another.'

inputs:
  target:
    description: 'Target branch you wish to update.'
    required: true

  base:
    description: 'Base branch to use to rebase target.'
    required: true

  token:
    description: 'GitHub token to use.'
    required: true

  force:
    description: 'Force push.'
    required: false
    default: 'false'

  remote:
    description: 'The remote to use'
    required: false
    default: 'origin'

  continue-on-error:
    description: 'Continue when rebasing fails'
    required: false
    default: 'true' # TODO: change to false in next major version

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ inputs.token }}
        ref: ${{ inputs.target }}
        fetch-depth: 0

    - name: 'Rebase'
      id: rebase
      shell: bash
      run: |
        FAILED=false
        git rebase "${{ inputs.remote }}/${{ inputs.base }}" || (FAILED=true && git rebase --abort)

        if [ "$FAILED" = true ]; then
          echo "failed=true" >> $GITHUB_OUTPUT

          if [ "${{ inputs.continue-on-error }}" = false ]; then
              exit 1
          fi
        fi

    - name: 'Push'
      shell: bash
      if: inputs.force != 'true' && steps.rebase.outputs.failed != 'true'
      run: |
        git push

    - name: 'Force push'
      shell: bash
      if: inputs.force == 'true' && steps.rebase.outputs.failed != 'true'
      run: |
        git push --force
