name: 'Rebase'
description: 'Rebase and update one branch with another.'

inputs:
  target:
    description: 'Target branch you wish to update.'
    required: true

  base:
    description: 'Base branch to use to rebase target.'
    required: true

  token:
    description: 'GitHub token to use.'
    required: true

  force:
    description: 'Force push.'
    required: false
    default: 'false'

  remote:
    description: 'The remote to use'
    required: false
    default: 'origin'

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ inputs.token }}
        ref: ${{ inputs.target }}
        fetch-depth: 0

    - name: 'Rebase'
      id: rebase
      shell: bash
      run: |
        git rebase "${{ inputs.remote }}/${{ inputs.base }}" || (echo "fail=true" >> $GITHUB_OUTPUT && git rebase --abort)

    - name: 'Push'
      shell: bash
      if: inputs.force != 'true' && steps.rebase.outputs.fail != 'true'
      run: |
        git push

    - name: 'Force push'
      shell: bash
      if: inputs.force == 'true' && steps.rebase.outputs.fail != 'true'
      run: |
        git push --force
