name: 'Create PDK root command'
description: 'Create the PDK root command for use with the app builder'

inputs:
  env-file:
    description: 'The env file to use'
    required: true

  image:
    description: 'PHP Docker image to use'
    required: false

outputs:
  root-command:
    description: 'The root command to use with the pdk builder'
    value: ${{ steps.create.outputs.root-command }}

runs:
  using: composite
  steps:
    - name: 'Create root command'
      id: create
      shell: bash
      env:
        ENV_FILE: ${{ inputs.env-file }}
        IMAGE: ${{ inputs.image }}
      #language=bash
      run: |
        if [ -z "$IMAGE" ]; then
          ROOT_COMMAND=''
        else
          ROOT_COMMAND="docker run -t --user $(id -u):$(id -g) --env-file=$ENV_FILE -v $PWD:/app -w /app $IMAGE"
        fi

        echo "root-command=$ROOT_COMMAND" >> $GITHUB_OUTPUT
