# Copy of ./hash-string but using the actions locally.

name: 'Hash string'
description: 'Hash a string'

inputs:
  string:
    description: 'The string to hash.'
    required: true

  separator:
    description: 'The separator that is used to join the lines.'
    required: false
    default: '\n'

  method:
    description: 'The hashing method to use.'
    required: false
    default: 'md5sum'

  mode:
    description: 'The mode to use for formatting. Set to "args" to deduplicate key-value pairs.'
    required: false
    default: ''

outputs:
  hash:
    description: 'The hashed string, empty if no string was provided.'
    value: ${{ steps.hash.outputs.hash }}

  string:
    description: 'The string that was hashed.'
    value: ${{ steps.format.outputs.string }}

runs:
  using: composite
  steps:
    - uses: ./format-string
      id: format
      with:
        string: ${{ inputs.string }}
        mode: ${{ inputs.mode }}
        sort: true
        deduplicate: true
        input-separator: ${{ inputs.separator }}
        output-separator: ' '

    - name: 'Hash string'
      id: hash
      shell: bash
      env:
        STRING: ${{ steps.format.outputs.string }}
        HASH_METHOD: ${{ inputs.method }}
      #language=bash
      run: |
        if [ -z "$STRING" ]; then
          echo "hash=" >> $GITHUB_OUTPUT
          exit 0
        fi

        HASH=$(echo -n "$STRING" | $(echo "$HASH_METHOD") | cut -d ' ' -f 1)

        echo "hash=$HASH" >> $GITHUB_OUTPUT
