name: 'Install bun dependencies'
description: 'Install bun and dependencies using cache'

inputs:
  bun-version:
    description: 'The bun version to use'
    default: '1.0.0'
    required: false

  bun-args:
    description: 'Arguments to use with bun install'
    default: '--frozen-lockfile'
    required: false

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4

    - uses: oven-sh/setup-bun@v1
      with:
        bun-version: ${{ inputs.bun-version }}

    - name: 'Get bun variables'
      id: variables
      shell: bash
      #language=bash
      run: |
        hash=$(bun pm hash-print || echo '')

        echo "cache-dir=$(bun pm cache)" >> $GITHUB_OUTPUT
        echo "hash=$hash" >> $GITHUB_OUTPUT

    - uses: myparcelnl/actions/create-cache-keys@v4
      id: keys-bun
      with:
        key: ${{ format('{0}{1}-bun', runner.os, runner.arch) }}
        input: |
          ${{ steps.variables.outputs.hash }}

    - name: 'Cache bun dependencies'
      if: steps.variables.outputs.hash != ''
      uses: actions/cache@v4
      with:
        path: ${{ steps.variables.outputs.cache-dir }}
        key: ${{ steps.keys-bun.outputs.key }}
        restore-keys: ${{ steps.keys-bun.outputs.restore-keys }}

    - name: 'Install bun dependencies'
      env:
        BUN_ARGS: ${{ inputs.bun-args }}
      shell: bash
      #language=bash
      run: |
        bun install $BUN_ARGS
