name: 'Create push prerelease artifacts'
description: 'Requires package to have been built'

inputs:
  image:
    description: 'PHP Docker image to use'
    required: true

outputs:
  version:
    description: 'The version that was released.'
    value: ${{ steps.version.outputs.version }}

runs:
  using: composite
  steps:
    - name: 'Determine version'
      id: version
      shell: bash
      #language=bash
      run: |
        version=$(npm pkg get version | sed 's/"//g')
        commitsSinceTag=$(git log --oneline v$version.. | wc -l)
        releaseVersion="$version-$commitsSinceTag"

        echo "version=$releaseVersion" >> $GITHUB_OUTPUT

    - uses: myparcelnl/actions/pdk-upgrade@v4
      with:
        image: ${{ inputs.image }}
        no-commit: true

    - uses: myparcelnl/actions/pdk-release@v4
      with:
        command: 'prerelease'
        image: ${{ inputs.image }}
        version: ${{ steps.version.outputs.version }}
