name: 'Create composer env'
description: 'Create env file for use with docker containers'

outputs:
  filename:
    description: 'The filename of the created env file'
    value: ${{ steps.create.outputs.filename }}

runs:
  using: composite
  steps:
    - name: 'Create env file'
      id: create
      shell: bash
      env:
        RUN_ID: ${{ github.run_id }}
      #language=bash
      run: |
        timestamp=$(date +%s)
        envFilename=".env-$RUN_ID-$timestamp.local.tmp"

        # Set fallback for COMPOSER_CACHE_DIR
        COMPOSER_CACHE_DIR=${COMPOSER_CACHE_DIR:-/tmp/cache/composer}

        # Add all present composer env variables to the env file
        printenv | (grep -E "^COMPOSER_" || true) > "$envFilename"

        echo "filename=$envFilename" >> $GITHUB_OUTPUT

        # Create the cache dir
        mkdir -p "$COMPOSER_CACHE_DIR"
