name: 'Create composer env'
description: 'Create env file for use with docker containers'

outputs:
  filename:
    description: 'The filename of the created env file'
    value: ${{ steps.create.outputs.filename }}

runs:
  using: composite
  steps:
    - name: 'Create env file'
      id: create
      env:
        RUN_ID: ${{ github.run_id }}
        DEBUG: ${{ runner.debug == '1' && 'true' || 'false' }}
        # Set fallback value
        COMPOSER_CACHE_DIR: ${{ env.COMPOSER_CACHE_DIR || '/tmp/cache/composer' }}
      shell: bash
      #language=bash
      run: |
        timestamp=$(date +%s)
        envFilename=".env-$RUN_ID-$timestamp.local.tmp"

        # Create the cache dir
        mkdir -p "$COMPOSER_CACHE_DIR"

        # Add all present composer env variables to the env file
        printenv | (grep -E "^COMPOSER_" || true) > "$envFilename"

        if [[ "$DEBUG" == 'true' ]]; then
          echo "::group::Created env file"
          cat "$envFilename"
          echo "::endgroup::"
        fi

        # Source the env file to make the variables available in subsequent steps
        source "$envFilename"

        echo "filename=$envFilename" >> $GITHUB_OUTPUT
